### ISSUE TITLE
[Bug]: [Notebook]An unexpected mistake occurred when using Deepfake Detection

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An unexpected mistake occurred when using Deepfake Detection.
https://github.com/towhee-io/examples/blob/main/video/deepfake_detection/1_deepfake_detection.ipynb
![image](https://user-images.githubusercontent.com/109071306/220275641-d3e40dfc-471e-4316-b3a4-9341374ccc01.png)
error:
```
Cloning the repo: towhee/deepfake... Be patient and waiting printing 'Successfully'.
正克隆到 '/Users/zilliz/.towhee/operators/towhee/deepfake/main'...
error: RPC 失败。HTTP 504 curl 22 The requested URL returned error: 504
fatal: 预期 'packfile'

Downloading __pycache__/kernel_utils.cpython-39.pyc:   0%|                                 | 0.00/12.1k [00:00<?, ?iB/s]



Downloading weights/final_999_DeepFakeClassifier_tf_efficientnet_b7_ns_0_23:   0%|           | 0.00/134 [00:00<?, ?iB/s]


Downloading requirements.txt:   0%|                                                         | 0.00/97.0 [00:00<?, ?iB/s]






Downloading README.md:   0%|                                                               | 0.00/1.25k [00:00<?, ?iB/s]




Downloading __pycache__/classifiers.cpython-39.pyc:   0%|                                  | 0.00/8.30k [00:00<?, ?iB/s]

Downloading .gitattributes:   0%|                                                          | 0.00/1.27k [00:00<?, ?iB/s]





Downloading weights/final_999_DeepFakeClassifier_tf_efficientnet_b7_ns_0_23: 100%|████| 134/134 [00:00<00:00, 12.2kiB/s]
Downloading __pycache__/kernel_utils.cpython-39.pyc: 100%|█████████████████████████| 12.1k/12.1k [00:00<00:00, 765kiB/s]
Downloading requirements.txt: 100%|█████████████████████████████████████████████████| 97.0/97.0 [00:00<00:00, 10.5kiB/s]
Downloading README.md: 100%|███████████████████████████████████████████████████████| 1.25k/1.25k [00:00<00:00, 156kiB/s]
Downloading __pycache__/classifiers.cpython-39.pyc: 100%|█████████████████████████| 8.30k/8.30k [00:00<00:00, 1.00MiB/s]
Downloading weights/final_777_DeepFakeClassifier_tf_efficientnet_b7_ns_0_31: 100%|████| 134/134 [00:00<00:00, 17.5kiB/s]
Downloading .gitattributes: 100%|██████████████████████████████████████████████████| 1.27k/1.27k [00:00<00:00, 175kiB/s]
Downloading __init__.py: 100%|████████████████████████████████████████████████████████| 592/592 [00:00<00:00, 88.3kiB/s]
Downloading classifiers.py: 100%|█████████████████████████████████████████████████| 12.5k/12.5k [00:00<00:00, 5.67MiB/s]
Downloading deepfake.png:   0%|                                                            | 0.00/54.1k [00:00<?, ?iB/s]
Downloading kernel_utils.py: 100%|████████████████████████████████████████████████| 15.5k/15.5k [00:00<00:00, 9.87MiB/s]
Downloading deepfake.png: 100%|███████████████████████████████████████████████████| 54.1k/54.1k [00:00<00:00, 1.00MiB/s]
Downloading deepfake.py: 100%|█████████████████████████████████████████████████████| 2.85k/2.85k [00:00<00:00, 678kiB/s]
Requirement already satisfied: dlib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 1)) (19.24.0)
Requirement already satisfied: facenet-pytorch in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (2.5.2)
Requirement already satisfied: albumentations in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: timm in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 4)) (0.6.12)
Requirement already satisfied: pytorch_toolbelt in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 5)) (0.6.2)
Requirement already satisfied: tensorboardx in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 6)) (2.6)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (3.6.2)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 8)) (4.64.1)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 9)) (1.5.2)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (9.3.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (1.23.5)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: torchvision in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (0.14.0)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (4.7.0.68)
Requirement already satisfied: qudida>=0.0.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (0.0.4)
Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (6.0)
Requirement already satisfied: scikit-image>=0.16.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (0.19.3)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (1.9.3)
Requirement already satisfied: torch>=1.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from timm->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 4)) (1.13.0)
Requirement already satisfied: huggingface-hub in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from timm->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: opencv-python>=4.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytorch_toolbelt->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 5)) (4.6.0.66)
Requirement already satisfied: protobuf<4,>=3.8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tensorboardx->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 6)) (3.20.3)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tensorboardx->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 6)) (21.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (1.0.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (4.38.0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 9)) (2022.6)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: scikit-learn>=0.19.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from qudida>=0.0.4->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (1.1.3)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from qudida>=0.0.4->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (4.4.0)
Requirement already satisfied: tifffile>=2019.7.26 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (2023.2.3)
Requirement already satisfied: PyWavelets>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: networkx>=2.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (2.8.8)
Requirement already satisfied: imageio>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (2.25.1)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from huggingface-hub->timm->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 4)) (3.8.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (1.26.13)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 2)) (3.4)
Requirement already satisfied: joblib>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations->-r /Users/zilliz/.towhee/operators/towhee/deepfake/main/requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: dlib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (19.24.0)
Requirement already satisfied: facenet-pytorch in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.5.2)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch) (9.3.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch) (1.23.5)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch) (2.28.1)
Requirement already satisfied: torchvision in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from facenet-pytorch) (0.14.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->facenet-pytorch) (2.1.1)
Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from torchvision->facenet-pytorch) (1.13.0)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from torchvision->facenet-pytorch) (4.4.0)
Requirement already satisfied: albumentations in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.3.0)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (1.9.3)
Requirement already satisfied: numpy>=1.11.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (1.23.5)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (4.7.0.68)
Requirement already satisfied: scikit-image>=0.16.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (0.19.3)
Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (6.0)
Requirement already satisfied: qudida>=0.0.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from albumentations) (0.0.4)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from qudida>=0.0.4->albumentations) (4.4.0)
Requirement already satisfied: scikit-learn>=0.19.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from qudida>=0.0.4->albumentations) (1.1.3)
Requirement already satisfied: networkx>=2.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (2.8.8)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (9.3.0)
Requirement already satisfied: tifffile>=2019.7.26 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (2023.2.3)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (21.3)
Requirement already satisfied: PyWavelets>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (1.4.1)
Requirement already satisfied: imageio>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-image>=0.16.1->albumentations) (2.25.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from packaging>=20.0->scikit-image>=0.16.1->albumentations) (3.0.9)
Requirement already satisfied: joblib>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (3.1.0)
Requirement already satisfied: pytorch_toolbelt in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.6.2)
Requirement already satisfied: torchvision in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytorch_toolbelt) (0.14.0)
Requirement already satisfied: scipy>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytorch_toolbelt) (1.9.3)
Requirement already satisfied: opencv-python>=4.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytorch_toolbelt) (4.6.0.66)
Requirement already satisfied: torch>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytorch_toolbelt) (1.13.0)
Requirement already satisfied: numpy>=1.14.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from opencv-python>=4.1->pytorch_toolbelt) (1.23.5)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from torch>=1.11.0->pytorch_toolbelt) (4.4.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from torchvision->pytorch_toolbelt) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from torchvision->pytorch_toolbelt) (9.3.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->torchvision->pytorch_toolbelt) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->torchvision->pytorch_toolbelt) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->torchvision->pytorch_toolbelt) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests->torchvision->pytorch_toolbelt) (3.4)
Requirement already satisfied: tensorboardx in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.6)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tensorboardx) (21.3)
Requirement already satisfied: protobuf<4,>=3.8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tensorboardx) (3.20.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tensorboardx) (1.23.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from packaging->tensorboardx) (3.0.9)
2023-02-21 15:28:33,881 - 4307764608 - operator_loader.py-operator_loader:131 - WARNING: The operator's format is outdated.
loading state dict /Users/zilliz/.towhee/operators/towhee/deepfake/main/weights/final_777_DeepFakeClassifier_tf_efficientnet_b7_ns_0_31
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 11
      3 ssl._create_default_https_context = ssl._create_unverified_context
      5 p = (
      6     pipe.input('path')
      7     .map('path', 'scores', ops.towhee.deepfake())
      8     .output('scores')
      9 )
---> 11 DataCollection(p('./deepfake_video/test/aagfhgtpmv.mp4').get_dict()).show()

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:149, in RuntimePipeline.__call__(self, *inputs)
    147 if self._enable_trace:
    148     self._time_profiler_list.append(graph.time_profiler)
--> 149 return graph(inputs)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:104, in _Graph.__call__(self, inputs)
    102 def __call__(self, inputs: Union[Tuple, List]):
    103     f = self.async_call(inputs)
--> 104     return f.result()

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:34, in _GraphResult.result(self)
     33 def result(self):
---> 34     ret = self._graph.result()
     35     del self._graph
     36     return ret

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py:87, in _Graph.result(self)
     85             errs += node.err_msg + '\n'
     86 if errs:
---> 87     raise RuntimeError(errs)
     88 end_edge_num = self._nodes['_output'].out_edges[0]
     89 res = self._data_queues[end_edge_num]

RuntimeError: Node-towhee/deepfake-0 runs failed, error msg: invalid load key, 'v'., Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 156, in _call
    return True, self._op(*inputs), None
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/towhee/engine/operator_registry.py", line 201, in wrapper_call
    return old_call(self, *args, **kws)
  File "/Users/zilliz/.towhee/operators/towhee/deepfake/main/deepfake.py", line 40, in __call__
    checkpoint = torch.load(path, map_location="cpu")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@wxywb  Can you help take a look?

**Comment by junjiejiangjjj** [comment]
fixed, please recheck

**Comment by NicoYuan1986** [comment]
https://github.com/towhee-io/examples/blob/main/video/deepfake_detection/1_deepfake_detection.ipynb
still failing 
![image](https://user-images.githubusercontent.com/109071306/220516738-31f56c7c-9d11-4ad8-99f3-a3697f631d13.png)

![image](https://user-images.githubusercontent.com/109071306/220516838-a65142b1-2e36-430c-a9e3-3084d5c85dae.png)

@wxywb  Could you help me look at it?

**Comment by wxywb** [comment]
this is due to incomplete uploaded weights, now it's re-uploaded to hub by git-lfs and should be solved, please try it again.

**Comment by NicoYuan1986** [comment]
Fixed.
